{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rover.campaigns",
    "module": "location",
    "version": "3.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "location-3.9.0.aar",
          "url": "location-3.9.0.aar",
          "size": 168914,
          "sha512": "5397057c146df473f5d9b52949242d53a581e421510f0ffbdb4de9f8c88d530ced492e9083e8f19751ba9ff4f59e49c0f2835c33ff843d14c27a5dd3fa87496a",
          "sha256": "e9f4a5c77d0fc92c635eee9fc333980cf3017576826fbb0883d399fe7442e1be",
          "sha1": "927e609479f42e956e84c76cd3cef885f265c214",
          "md5": "1425f9fb5963d99df5dc26b6b70ffec9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "io.rover.campaigns",
          "module": "core",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-nearby",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "location-3.9.0.aar",
          "url": "location-3.9.0.aar",
          "size": 168914,
          "sha512": "5397057c146df473f5d9b52949242d53a581e421510f0ffbdb4de9f8c88d530ced492e9083e8f19751ba9ff4f59e49c0f2835c33ff843d14c27a5dd3fa87496a",
          "sha256": "e9f4a5c77d0fc92c635eee9fc333980cf3017576826fbb0883d399fe7442e1be",
          "sha1": "927e609479f42e956e84c76cd3cef885f265c214",
          "md5": "1425f9fb5963d99df5dc26b6b70ffec9"
        }
      ]
    }
  ]
}
