{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rover.campaigns",
    "module": "core",
    "version": "3.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.9.1.aar",
          "url": "core-3.9.1.aar",
          "size": 629015,
          "sha512": "f04c04277338756229982b920febadc3506756d6dd330f9fd2954d29e582df807509f14c826dd60d5c6858c5039a5e75c56223394158ed805dc784e3c4446f3c",
          "sha256": "84686bb767b7e369aaaccef454f87f322617590ee136d0cad81db2c6e420adf0",
          "sha1": "a03d249e9b31cb32aa3f2517a29dfe46226213fc",
          "md5": "6d962b2dc8d5914f8914c312d612cfaa"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.9.1.aar",
          "url": "core-3.9.1.aar",
          "size": 629015,
          "sha512": "f04c04277338756229982b920febadc3506756d6dd330f9fd2954d29e582df807509f14c826dd60d5c6858c5039a5e75c56223394158ed805dc784e3c4446f3c",
          "sha256": "84686bb767b7e369aaaccef454f87f322617590ee136d0cad81db2c6e420adf0",
          "sha1": "a03d249e9b31cb32aa3f2517a29dfe46226213fc",
          "md5": "6d962b2dc8d5914f8914c312d612cfaa"
        }
      ]
    }
  ]
}
